# Disable the newline at the start of the prompt
add_newline = false

format = """\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $time\
    $elixir\
    $golang\
    $haskell\
    $nodejs\
    $php\
    $rust\
    $cmd_duration\
    $line_break\
    $character\
    """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[time]
disabled = true
format = "%Y-%m-%d %H:%M:%S"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
enabled = false

[directory]
style = "bright-white"

[character]
symbol = "❯"
style_success = "bold white"
style_failure = "bold bright-red"
use_symbol_for_status = false

[git_branch]
symbol = " "
style = "bold bright-green"

[git_state]
style = "bold bright-green"

[git_status]
style = "bright-red"
ahead = "  ${count}"
behind = "  ${count}"
diverged = "  "
untracked = "  ${count}"
stashed = "  ${count}"
modified = "  ${count}"
staged = "  ${count}"
renamed = "  "
deleted = "  "
format = "([·$all_status$ahead_behind]($style) )"

[elixir]
symbol = "瞧 "

[haskell]
symbol = "益 "

[rust]
symbol = "謹 "

[docker_context]
symbol = "滛 "

[kubernetes]
symbol = "窱 "

[nodejs]
symbol = "者 "

[ruby]
symbol = "諭 "

[python]
symbol = "諸 "

[php]
symbol = "襁 "

[golang]
symbol = "瘝 "
