# Disable the newline at the start of the prompt
add_newline = false

# Overwrite a default_prompt_order and  use custom prompt_order
prompt_order = [
    # "username",
    # "hostname",
    # "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "time",
    # "hg_branch",
    # "docker_context",
    # "package",
    # "dotnet",
    "elixir",
    # "elm",
    # "golang",
    "haskell",
    # "java",
    # "julia",
    "nodejs",
    # "php",
    # "python",
    # "ruby",
    "rust",
    # "terraform",
    # "nix_shell",
    # "conda",
    # "memory_usage",
    # "aws",
    # "env_var",
    # "crystal",
    "cmd_duration",
    # "custom",
    "line_break",
    # "jobs",
    # "battery",
    "character",
]

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[time]
disabled = true
format = "%Y-%m-%d %H:%M:%S"

[cmd_duration]
min_time = 500
prefix = "took "
enabled = false

[directory]
style = "bright-white"

[character]
symbol = "❯"
style_success = "bold white"
style_failure = "bold bright-red"
use_symbol_for_status = false

[git_branch]
symbol = " "
style = "bold bright-green"

[git_state]
style = "bold bright-green"

[git_status]
style = "bright-red"
ahead = "  "
behind = "  "
diverged = "  "
untracked = "  "
untracked_count.enabled = true
stashed = "  "
modified = "  "
modified_count.enabled = true
staged = "  "
staged_count.enabled = true
renamed = "  "
deleted = "  "
show_sync_count = true
prefix = "·"
suffix = " "
