;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cc/comment-or-uncomment-line-or-region
        cc/copy-character-from-above
        cc/join-with-next-line
        cc/smarter-move-beginning-of-line
        default-indent-new-line
        dired-maybe-insert-subdir
        forward-sexp
        haskell-indentation-common-electric-command
        indent-for-tab-command
        kill-sexp
        markdown-cycle
        markdown-outdent-or-delete
        org-delete-char
        org-end-of-line
        org-kill-line
        org-self-insert-command
        paredit-backslash
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-meta-doublequote
        paredit-open-round
        paredit-splice-sexp
        paredit-splice-sexp-killing-backward
        paredit-wrap-round
        rjsx-delete-creates-full-tag
        rjsx-electric-gt
        string-inflection-all-cycle
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cc/duplicate-line-or-region-above
        counsel-M-x
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/insert-letters-and-exit
        hydra-multiple-cursors/mc/insert-numbers-and-exit
        hydra-multiple-cursors/mc/mark-all-in-region-regexp-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/nil
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        hydra-multiple-cursors/nil
        org-cycle
        swiper
        ))
