;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cc/copy-character-from-above
        cc/smarter-move-beginning-of-line
        forward-sexp
        haskell-indentation-common-electric-command
        indent-for-tab-command
        kill-sexp
        org-delete-char
        org-end-of-line
        org-self-insert-command
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-meta-doublequote
        paredit-splice-sexp
        paredit-splice-sexp-killing-backward
        paredit-wrap-round
        rjsx-delete-creates-full-tag
        ))

(setq mc/cmds-to-run-once
      '(
        cc/duplicate-line-or-region-above
        counsel-M-x
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/insert-letters-and-exit
        hydra-multiple-cursors/mc/insert-numbers-and-exit
        hydra-multiple-cursors/mc/mark-all-in-region-regexp-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/nil
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        org-cycle
        swiper
        ))
